### ISSUE TITLE
If you start using a platform whitelist - put it in the release notes.

### ISSUE THREAD

**Issue by kayosiii** [TheFoundry-Modo/UnrealPlugin#9]
Grrrr - This just cost me several hours while I tried to figure out why the plugin stopped working for me. [windows is hard locking for me while compiling ue4] so I am developing on Linux

**Comment by heqilu** [comment]
We do not officially support Linux, so I completely forgot this point.
I will put the information in the Readme.

**Comment by heqilu** [comment]
I have updated the readme.
Good to know that "WhiteList" actually marks everything else to black list .....

**Comment by heqilu** [comment]
I feel you pain and thank you very much for the feedback.

Thanks.

**Comment by kayosiii** [comment]
For the record; your plugin works fine on Linux (at least on Arch Linux) :)  - after Linux is added to the whitelist of course.

**Comment by heqilu** [comment]
If we add Linux to the whitelist, we have to support Linux continuously. Do you want to do that?
Another issue is Linux has so many redistributions, if the plugin doesn't work on some of them, users will complain. So, unless there are many users request that support, it is better to not officially announce it.

Maybe I should simply remove the whitelist.

**Comment by kayosiii** [comment]
My fork does compile on Linux so I guess I am already doing that :p

I can't imagine having to use many libraries outside the existing UE4
ecosystem so I don't antisipate too many issues. (assuming that the clang +
stdlib linker issues have been sorted out).
Basically if UE4 compiles and works the plugin should be fine also.

If you do decide to do Binaries somewhere down the track you only really
need to support what the current version of Modo supports.
